# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 22:49
from __future__ import unicode_literals

import bitfield.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0017_autoinstaller_installerrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('achieved_icon', models.ImageField(blank=True, upload_to='achievements/achieved_icon')),
                ('unachieved_icon', models.ImageField(blank=True, upload_to='achievements/unachieved_icon')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', bitfield.models.BitField((('integer', 'Integer'), ('float', 'Float'), ('average', 'Average')), default=None)),
                ('name', models.CharField(max_length=200)),
                ('increment_only', models.BooleanField(default=False)),
                ('max_change', models.PositiveIntegerField(blank=True, null=True)),
                ('min_change', models.PositiveIntegerField(blank=True, null=True)),
                ('max_value', models.PositiveIntegerField(blank=True, null=True)),
                ('window', models.PositiveIntegerField(blank=True, null=True)),
                ('default_value', models.IntegerField(blank=True, null=True)),
                ('aggregated', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingame_api.Achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingame_api.Stat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingame_api.Stat'),
        ),
    ]
