# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingame_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
